spring.application.name=order-service
server.port=8082
spring.datasource.url=jdbc:postgresql://postgres:5432/platform
spring.datasource.username=platform
spring.datasource.password=platform
spring.jpa.hibernate.ddl-auto=update
