spring.application.name=order-service
server.port=8082
spring.datasource.url=jdbc:postgresql://postgres:5432/platform
spring.datasource.username=platform
spring.datasource.password=platform
spring.jpa.hibernate.ddl-auto=update
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=10s